# Generated by Django 5.2.17 on 2026-09-21 23:09

import django.db.models.deletion
import mvp_compliance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name this document is known by, such as “Privacy policy”.', max_length=100, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(editable=False, help_text="This version's position among its document's versions, assigned automatically.", verbose_name='number')),
                ('markdown', models.TextField(help_text='The wording of this version, written in Markdown.', verbose_name='markdown')),
                ('html', models.TextField(blank=True, help_text='The HTML a reader is served, rendered from the markdown once, at publication. Empty for a draft that has never been published.', verbose_name='html')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('current', 'Current'), ('superseded', 'Superseded')], default='draft', editable=False, help_text='Whether this version is a draft, the version currently in force, or superseded by a later one.', max_length=10, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, editable=False, help_text='The moment this version was published. Null for a draft that has never been published.', null=True, verbose_name='published at')),
                ('document', models.ForeignKey(help_text='The document this version belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='mvp_compliance.document', verbose_name='document')),
            ],
            options={
                'verbose_name': 'version',
                'verbose_name_plural': 'versions',
                'ordering': ['document', 'number'],
                'constraints': [models.UniqueConstraint(fields=('document', 'number'), name='unique_version_number_per_document'), models.UniqueConstraint(condition=models.Q(('status', 'current')), fields=('document',), name='one_current_version_per_document'), models.CheckConstraint(condition=models.Q(models.Q(('html', ''), ('published_at__isnull', True), ('status', 'draft')), models.Q(('status__in', ['current', 'superseded']), ('published_at__isnull', False), models.Q(('html', ''), _negated=True)), _connector='OR'), name='version_status_agrees_with_its_publication')],
            },
            managers=[
                ('objects', mvp_compliance.models.VersionManager()),
            ],
        ),
    ]
