# Generated by Django 5.2.17 on 2026-09-21 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name this document is known by, such as “Privacy policy”.', max_length=100, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(editable=False, help_text="This version's position among its document's versions, assigned automatically.", verbose_name='number')),
                ('markdown', models.TextField(help_text='The wording of this version, written in Markdown.', verbose_name='markdown')),
                ('document', models.ForeignKey(help_text='The document this version belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='mvp_compliance.document', verbose_name='document')),
            ],
            options={
                'verbose_name': 'version',
                'verbose_name_plural': 'versions',
                'ordering': ['document', 'number'],
                'constraints': [models.UniqueConstraint(fields=('document', 'number'), name='unique_version_number_per_document')],
            },
        ),
    ]
