# Generated by Django 6.1.1 on 2026-10-09 11:53

import django.core.validators
import django.db.models.deletion
import mvp_compliance.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name this document is known by, such as “Privacy policy”.', max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(help_text="The document's identifier in its address, such as “privacy-policy”.", max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Use lowercase letters, digits and single hyphens only.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*\\Z'), mvp_compliance.models.unreserved_slug], verbose_name='slug')),
                ('kind', models.CharField(choices=[('agreed', 'Agreed to'), ('notice', 'Notice')], default='agreed', help_text='Whether people agree to this document, such as a privacy policy, or only read it, such as an impressum. Nobody is ever asked to accept a notice.', max_length=10, verbose_name='kind')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(editable=False, help_text="The accepted user's primary key, held as text and written once, when this record is made. The `user` foreign key is cleared when that account is removed, so without this field the record could no longer say whose it is or be found among that person's others.", max_length=255, verbose_name='subject')),
                ('accepted_at', models.DateTimeField(db_index=True, editable=False, help_text='The moment this acceptance was recorded. Set once, when the record is made, and never rewritten.', verbose_name='accepted at')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="The address the request came from when this acceptance was recorded. Held only when the host project has turned that on and supplied the request — personal data about someone who did not ask for it to be kept, so it is the host project's decision.", null=True, verbose_name='IP address')),
                ('user', models.ForeignKey(blank=True, help_text='The account that accepted this version, at the time it accepted it. Null only ever means the account has since been removed — never that the acceptor was unknown.', null=True, on_delete=mvp_compliance.models.keep_or_remove_acceptances, related_name='compliance_acceptances', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'acceptance',
                'verbose_name_plural': 'acceptances',
                'ordering': ['accepted_at', 'id'],
            },
            managers=[
                ('objects', mvp_compliance.models.AcceptanceManager()),
            ],
        ),
        migrations.CreateModel(
            name='Disclosure',
            fields=[
            ],
            options={
                'verbose_name': 'disclosure',
                'verbose_name_plural': 'everything held about a person',
                'permissions': [('produce_disclosure', 'Can produce everything held about a person')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mvp_compliance.acceptance',),
            managers=[
                ('objects', mvp_compliance.models.AcceptanceManager()),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, editable=False, help_text="The year this version was published and its place among the document's versions published that year, such as 2026.2. Assigned at publication. Empty for a draft.", max_length=20, null=True, verbose_name='number')),
                ('markdown', models.TextField(help_text='The wording of this version, written in Markdown.', verbose_name='markdown')),
                ('html', models.TextField(blank=True, help_text='The HTML a reader is served, rendered from the markdown once, at publication. Empty for a draft that has never been published.', verbose_name='html')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('current', 'Current'), ('superseded', 'Superseded')], default='draft', editable=False, help_text='Whether this version is a draft, the version currently in force, or superseded by a later one.', max_length=10, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, editable=False, help_text='The moment this version was published. Null for a draft that has never been published.', null=True, verbose_name='published at')),
                ('publisher_subject', models.CharField(blank=True, db_index=True, default='', editable=False, help_text="The publisher's primary key as text, written once at publication. It lets the version say an account was since removed after the link to it is cleared. Empty when nobody was recorded.", max_length=255, verbose_name='publisher subject')),
                ('document', models.ForeignKey(help_text='The document this version belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='mvp_compliance.document', verbose_name='document')),
                ('publisher', models.ForeignKey(blank=True, editable=False, help_text='The account that published this version. Empty for a draft, for a version published from code with nobody named, and once that account is removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='publisher')),
            ],
            options={
                'verbose_name': 'version',
                'verbose_name_plural': 'versions',
                'ordering': ['document', models.OrderBy(models.F('published_at'), nulls_last=True), 'pk'],
                'permissions': [('publish_version', 'Can publish a version')],
            },
            managers=[
                ('objects', mvp_compliance.models.VersionManager()),
            ],
        ),
        migrations.AddField(
            model_name='acceptance',
            name='version',
            field=models.ForeignKey(help_text='The published version this acceptance names. Never a draft — recording an acceptance of one is refused.', on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='mvp_compliance.version', verbose_name='version'),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(fields=('document', 'number'), name='unique_version_number_per_document'),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'current')), fields=('document',), name='one_current_version_per_document'),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('html', ''), ('number__isnull', True), ('published_at__isnull', True), ('publisher__isnull', True), ('publisher_subject', ''), ('status', 'draft')), models.Q(('status__in', ['current', 'superseded']), ('number__isnull', False), ('published_at__isnull', False), models.Q(('html', ''), _negated=True)), _connector='OR'), name='version_status_agrees_with_its_publication'),
        ),
        migrations.AddConstraint(
            model_name='acceptance',
            constraint=models.UniqueConstraint(fields=('subject', 'version'), name='one_acceptance_per_person_per_version'),
        ),
    ]
