# Generated by Django 5.2.17 on 2026-09-22 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import mvp_compliance.models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(editable=False, help_text="The accepted user's primary key, held as text and written once, when this record is made. The `user` foreign key is cleared when that account is removed, so without this field the record could no longer say whose it is or be found among that person's others.", max_length=255, verbose_name='subject')),
                ('accepted_at', models.DateTimeField(db_index=True, editable=False, help_text='The moment this acceptance was recorded. Set once, when the record is made, and never rewritten.', verbose_name='accepted at')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="The address the request came from when this acceptance was recorded. Held only when the host project has turned that on and supplied the request — personal data about someone who did not ask for it to be kept, so it is the host project's decision.", null=True, verbose_name='IP address')),
                ('user', models.ForeignKey(blank=True, help_text='The account that accepted this version, at the time it accepted it. Null only ever means the account has since been removed — never that the acceptor was unknown.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_acceptances', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('version', models.ForeignKey(help_text='The published version this acceptance names. Never a draft — recording an acceptance of one is refused.', on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='mvp_compliance.version', verbose_name='version')),
            ],
            options={
                'verbose_name': 'acceptance',
                'verbose_name_plural': 'acceptances',
            },
            managers=[
                ('objects', mvp_compliance.models.AcceptanceManager()),
            ],
        ),
    ]
