# Generated by Django 5.2.17 on 2026-09-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='published_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='The moment this version was published. Null for a draft that has never been published.', null=True, verbose_name='published at'),
        ),
        migrations.AddField(
            model_name='version',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('current', 'Current'), ('superseded', 'Superseded')], default='draft', editable=False, help_text='Whether this version is a draft, the version currently in force, or superseded by a later one.', max_length=10, verbose_name='status'),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('status', 'draft')), models.Q(models.Q(('status', 'draft'), _negated=True), ('published_at__isnull', False)), _connector='OR'), name='version_status_agrees_with_published_at'),
        ),
    ]
