# Generated by Django 5.2.17 on 2026-09-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['document', 'number'], 'permissions': [('publish_version', 'Can publish a version')], 'verbose_name': 'version', 'verbose_name_plural': 'versions'},
        ),
    ]
