# Generated by Django 5.2.17 on 2026-09-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_compliance', '0002_version_published_at_version_status_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'current')), fields=('document',), name='one_current_version_per_document'),
        ),
    ]
