# Generated by Django 5.2.17 on 2026-09-22 22:57

from django.db import migrations

import mvp_compliance.models


class Migration(migrations.Migration):
    dependencies = [
        ("mvp_compliance", "0003_acceptance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disclosure",
            fields=[],
            options={
                "verbose_name": "disclosure",
                "verbose_name_plural": "everything held about a person",
                "permissions": [
                    ("produce_disclosure", "Can produce everything held about a person")
                ],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("mvp_compliance.acceptance",),
            managers=[
                ("objects", mvp_compliance.models.AcceptanceManager()),
            ],
        ),
    ]
