# Generated by Django 5.2.17 on 2026-09-22 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_compliance', '0003_acceptance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceptance',
            options={'ordering': ['accepted_at', 'id'], 'verbose_name': 'acceptance', 'verbose_name_plural': 'acceptances'},
        ),
        migrations.AddConstraint(
            model_name='acceptance',
            constraint=models.UniqueConstraint(fields=('subject', 'version'), name='one_acceptance_per_person_per_version'),
        ),
    ]
