# Generated by Django 5.2.17 on 2026-09-21 21:30

import mvp_compliance.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_compliance', '0003_version_one_current_version_per_document'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='version',
            managers=[
                ('objects', mvp_compliance.models.VersionManager()),
            ],
        ),
    ]
