# Generated by Django 5.2.17 on 2026-09-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_compliance', '0004_alter_version_managers'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='version',
            name='version_status_agrees_with_published_at',
        ),
        migrations.AddField(
            model_name='version',
            name='html',
            field=models.TextField(blank=True, help_text='The HTML a reader is served, rendered from the markdown once, at publication. Empty for a draft that has never been published.', verbose_name='html'),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('html', ''), ('published_at__isnull', True), ('status', 'draft')), models.Q(models.Q(('status', 'draft'), _negated=True), ('published_at__isnull', False), models.Q(('html', ''), _negated=True)), _connector='OR'), name='version_status_agrees_with_published_at'),
        ),
    ]
