# Generated by Django 5.2.17 on 2026-09-24 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_compliance', '0004_disclosure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='version',
            name='version_status_agrees_with_its_publication',
        ),
        migrations.AddField(
            model_name='version',
            name='publisher',
            field=models.ForeignKey(blank=True, editable=False, help_text='The account that published this version. Empty for a draft, for a version published from code with nobody named, and once that account is removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='publisher'),
        ),
        migrations.AddField(
            model_name='version',
            name='publisher_subject',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, help_text="The publisher's primary key as text, written once at publication. It lets the version say an account was since removed after the link to it is cleared. Empty when nobody was recorded.", max_length=255, verbose_name='publisher subject'),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('html', ''), ('published_at__isnull', True), ('publisher__isnull', True), ('publisher_subject', ''), ('status', 'draft')), models.Q(('status__in', ['current', 'superseded']), ('published_at__isnull', False), models.Q(('html', ''), _negated=True)), _connector='OR'), name='version_status_agrees_with_its_publication'),
        ),
    ]
