# Generated by Django 5.2.17 on 2026-09-22 16:31

from django.conf import settings
from django.db import migrations, models

import mvp_compliance.models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_compliance', '0004_alter_acceptance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptance',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The account that accepted this version, at the time it accepted it. Null only ever means the account has since been removed — never that the acceptor was unknown.', null=True, on_delete=mvp_compliance.models.keep_or_remove_acceptances, related_name='compliance_acceptances', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
