# Generated by Django 6.1.1 on 2026-09-25 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_compliance', '0005_version_publisher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['document', models.OrderBy(models.F('published_at'), nulls_last=True), 'pk'], 'permissions': [('publish_version', 'Can publish a version')], 'verbose_name': 'version', 'verbose_name_plural': 'versions'},
        ),
        migrations.RemoveConstraint(
            model_name='version',
            name='version_status_agrees_with_its_publication',
        ),
        migrations.AlterField(
            model_name='version',
            name='number',
            field=models.CharField(blank=True, editable=False, help_text="The year this version was published and its place among the document's versions published that year, such as 2026.2. Assigned at publication. Empty for a draft.", max_length=20, null=True, verbose_name='number'),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('html', ''), ('number__isnull', True), ('published_at__isnull', True), ('publisher__isnull', True), ('publisher_subject', ''), ('status', 'draft')), models.Q(('status__in', ['current', 'superseded']), ('number__isnull', False), ('published_at__isnull', False), models.Q(('html', ''), _negated=True)), _connector='OR'), name='version_status_agrees_with_its_publication'),
        ),
    ]
