# Generated by Django 6.1.1 on 2026-09-26 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_compliance', '0006_version_numbered_at_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(default='', help_text="The document's identifier in its address, such as “privacy-policy”.", max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Use lowercase letters, digits and single hyphens only.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*\\Z')], verbose_name='slug'),
            preserve_default=False,
        ),
    ]
