# Generated by Django 6.1.1 on 2026-09-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_compliance', '0007_document_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('agreed', 'Agreed to'), ('notice', 'Notice')], default='agreed', help_text='Whether people agree to this document, such as a privacy policy, or only read it, such as an impressum. Nobody is ever asked to accept a notice.', max_length=10, verbose_name='kind'),
        ),
    ]
