# Generated by Django 6.1.1 on 2026-10-01 21:31

import django.core.validators
import mvp_compliance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_compliance', '0008_document_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(help_text="The document's identifier in its address, such as “privacy-policy”.", max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Use lowercase letters, digits and single hyphens only.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*\\Z'), mvp_compliance.models.unreserved_slug], verbose_name='slug'),
        ),
    ]
